export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <div className="mb-8">
          <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
          <p className="text-gray-600">Last updated: January 25, 2026</p>
        </div>

        <div className="prose prose-sm max-w-none">
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">
              1. Nature of Electronic Record
            </h2>
            <p className="mb-4">
              These Terms of Service constitute an electronic record under the
              Information Technology Act, 2000 (&quot;IT Act&quot;) and the
              rules thereunder, as amended from time to time, including the
              Information Technology (Intermediary Guidelines and Digital Media
              Ethics Code) Rules, 2021. This electronic record is generated by a
              computer system and does not require any physical or digital
              signatures.
            </p>
            <p className="mb-4">
              By accessing and using this website and services operated by Walle
              Arena, you acknowledge that you have read, understood, and agree to
              be bound by these Terms of Service and our Privacy Policy. If you
              do not agree to these terms, please do not use this service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">
              2. Eligibility and Capacity to Contract
            </h2>
            <p className="mb-4">
              By using this website and registering for our services, you
              represent and warrant that:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>
                You are at least 18 years of age and legally competent to enter
                into binding contracts under the Indian Contract Act, 1872
              </li>
              <li>
                If you are below 18 years, you have obtained consent from your
                parent or legal guardian to use this service
              </li>
              <li>
                You are not barred or otherwise legally prohibited from using
                this service under the laws of India
              </li>
              <li>
                All information provided by you during registration is accurate,
                current, and complete
              </li>
            </ul>
            <p className="mb-4">
              Walle Arena reserves the right to refuse service, terminate
              accounts, or cancel registrations if eligibility criteria are not
              met.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">3. Account Security and Responsibility</h2>
            <p className="mb-4">
              When you register for our service, you agree to:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>
                Provide accurate, current, and complete information during the
                registration process
              </li>
              <li>
                Maintain and promptly update your registration information to
                keep it accurate and complete
              </li>
              <li>
                Maintain the confidentiality of your account credentials and be
                fully responsible for all activities under your account
              </li>
              <li>
                Notify us immediately of any unauthorized use of your account or
                security breach at <strong>support@wallearena.com</strong>
              </li>
              <li>
                Accept responsibility for all activities and transactions
                conducted through your account
              </li>
            </ul>
            <p className="mb-4">
              Walle Arena will not be liable for any loss or damage arising from
              your failure to maintain account security.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">
              4. Payment Terms and Razorpay Integration
            </h2>
            <p className="mb-4">
              All payments for tournament registration are processed through
              Razorpay, a secure and PCI-DSS Level 1 compliant payment gateway.
              By proceeding with payment, you acknowledge and agree that:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>
                All payment transactions are subject to Razorpay&apos;s Terms of
                Service and Privacy Policy in addition to ours
              </li>
              <li>
                You authorize Walle Arena to charge the specified registration
                fee to your chosen payment method through Razorpay
              </li>
              <li>
                Walle Arena does not store or have access to your complete credit
                card, debit card, or net banking credentials
              </li>
              <li>
                Payment information is encrypted and processed securely by
                Razorpay in compliance with international security standards
              </li>
              <li>
                All fees are stated in Indian Rupees (INR) and are inclusive of
                applicable taxes unless stated otherwise
              </li>
              <li>
                Registration is confirmed only upon successful payment
                verification by Razorpay
              </li>
            </ul>
            <p className="mb-4">
              <strong>Refund Policy:</strong> All payments are subject to our
              Refund and Return Policy. Please refer to our dedicated Refund
              Policy page for detailed information on eligibility, timelines, and
              procedures.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">
              5. Prohibited Activities and Restricted Categories
            </h2>
            <p className="mb-4">
              In compliance with Razorpay&apos;s acceptable use policy and Indian
              law, you agree not to use this service for any unlawful or
              prohibited purposes, including but not limited to:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>
                Providing false, inaccurate, or misleading information during
                registration
              </li>
              <li>
                Engaging in fraudulent activities, identity theft, or impersonation
              </li>
              <li>
                Uploading viruses, malware, or any malicious code that may harm
                our systems
              </li>
              <li>
                Attempting to gain unauthorized access to our servers, databases,
                or networks
              </li>
              <li>
                Interfering with or disrupting the website&apos;s proper
                functioning or servers
              </li>
              <li>
                Using automated systems (bots, scripts, crawlers) to access the
                service without authorization
              </li>
              <li>
                Engaging in any activity that violates Indian laws, including the
                IT Act, 2000, Indian Penal Code, 1860, or Consumer Protection
                Act, 2019
              </li>
              <li>
                Attempting to bypass payment systems or manipulate transaction
                records
              </li>
              <li>
                Submitting counterfeit documents or forged identification
              </li>
              <li>
                Harassing, threatening, or abusing other users or Walle Arena
                staff
              </li>
            </ul>
            <p className="mb-4">
              Violation of these prohibitions may result in immediate termination
              of your account, forfeiture of registration fees, and potential
              legal action.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">6. Intellectual Property Rights</h2>
            <p className="mb-4">
              All content on this website, including but not limited to text,
              graphics, logos, images, photographs, videos, audio clips, digital
              downloads, data compilations, and software, is the property of
              Walle Arena or its licensors and is protected by Indian and
              international copyright, trademark, and other intellectual property
              laws.
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>
                You may not reproduce, distribute, modify, create derivative
                works, publicly display, or exploit any content without our
                express written permission
              </li>
              <li>
                The Walle Arena name, logo, and all related marks are trademarks
                or registered trademarks of Walle Arena
              </li>
              <li>
                Unauthorized use of our trademarks or intellectual property may
                violate copyright, trademark, and other laws
              </li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">7. User Content and License</h2>
            <p className="mb-4">
              When you upload content to our platform (including photos,
              documents, and personal information), you represent and warrant that:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>
                You own or have the necessary rights to the content you upload
              </li>
              <li>
                The content does not infringe upon any third-party intellectual
                property, privacy, or publicity rights
              </li>
              <li>
                The content does not contain viruses, malware, or harmful code
              </li>
              <li>
                The content is not obscene, defamatory, libelous, threatening,
                pornographic, harassing, hateful, racially or ethnically
                offensive, or otherwise illegal
              </li>
            </ul>
            <p className="mb-4">
              By uploading content, you grant Walle Arena a non-exclusive,
              worldwide, royalty-free, perpetual, irrevocable license to use,
              reproduce, store, modify, and display that content solely for the
              purposes of processing your registration, providing tournament
              services, and internal record-keeping.
            </p>
            <p className="mb-4">
              Walle Arena reserves the right to remove any content that violates
              these Terms or is otherwise objectionable, without prior notice.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">2. Use License</h2>
            <p className="mb-4">
              Permission is granted to temporarily download one copy of the
              materials (information or software) on Walle Registration&apos;s
              website for personal, non-commercial transitory viewing only. This
              is the grant of a license, not a transfer of title, and under this
              license you may not:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>Modifying or copying the materials</li>
              <li>
                Using the materials for any commercial purpose or for any public
                display
              </li>
              <li>
                Attempting to decompile or reverse engineer any software
                contained on the website
              </li>
              <li>
                Removing any copyright or other proprietary notations from the
                materials
              </li>
              <li>
                Transferring the materials to another person or
                &quot;mirroring&quot; the materials on any other server
              </li>
              <li>Uploading viruses or malicious code</li>
              <li>Interfering with the website&apos;s proper functioning</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">8. Website Use License</h2>
            <p className="mb-4">
              Permission is granted to temporarily access and use this website
              for personal, non-commercial purposes related to tournament
              registration only. This is a limited license, not a transfer of
              title. Under this license, you may not:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>Modify, copy, or reproduce website materials for commercial use</li>
              <li>
                Use the materials for any commercial purpose or public display
                without authorization
              </li>
              <li>
                Attempt to decompile, reverse engineer, or disassemble any
                software or code on the website
              </li>
              <li>
                Remove any copyright, trademark, or other proprietary notations
                from materials
              </li>
              <li>
                Transfer materials to another person or mirror materials on any
                other server
              </li>
              <li>
                Upload viruses, worms, or any code of a destructive nature
              </li>
              <li>
                Interfere with or disrupt the website or servers/networks
                connected to the website
              </li>
            </ul>
            <p className="mb-4">
              This license shall automatically terminate if you violate any of
              these restrictions. Upon termination, you must immediately cease
              all use of the website and destroy any downloaded materials.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">9. Disclaimer of Warranties</h2>
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">9. Disclaimer of Warranties</h2>
            <p className="mb-4">
              The materials and services on Walle Arena&apos;s website are
              provided on an &apos;as is&apos; and &apos;as available&apos;
              basis. Walle Arena makes no warranties, expressed or implied, and
              hereby disclaims and negates all warranties including, without
              limitation:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>
                Implied warranties of merchantability or fitness for a particular
                purpose
              </li>
              <li>
                Non-infringement of intellectual property or violation of third-party
                rights
              </li>
              <li>
                Accuracy, completeness, reliability, or timeliness of information
              </li>
              <li>
                Uninterrupted, secure, or error-free operation of the website
              </li>
              <li>
                Freedom from viruses or other harmful components
              </li>
            </ul>
            <p className="mb-4">
              To the fullest extent permitted by law, Walle Arena does not
              warrant that defects will be corrected or that the website is free
              of viruses or other harmful components.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">10. Limitation of Liability</h2>
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">10. Limitation of Liability</h2>
            <p className="mb-4">
              To the maximum extent permitted by applicable law, in no event
              shall Walle Arena, its officers, directors, employees, agents,
              partners, or suppliers be liable for:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>
                Any indirect, incidental, special, consequential, or punitive
                damages
              </li>
              <li>
                Loss of profits, revenue, data, goodwill, or other intangible
                losses
              </li>
              <li>
                Damages arising from your use or inability to use the service
              </li>
              <li>
                Unauthorized access to or alteration of your transmissions or data
              </li>
              <li>
                Statements or conduct of any third party on the service
              </li>
              <li>
                Any other matter relating to the service
              </li>
            </ul>
            <p className="mb-4">
              This limitation applies whether the alleged liability is based on
              contract, tort, negligence, strict liability, or any other basis,
              even if Walle Arena has been advised of the possibility of such
              damage.
            </p>
            <p className="mb-4">
              Our total liability to you for all claims arising from or related
              to the service shall not exceed the amount you paid to us for the
              service (i.e., the registration fee).
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">
              11. Accuracy of Materials and Information
            </h2>
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">
              11. Accuracy of Materials and Information
            </h2>
            <p className="mb-4">
              While we strive to provide accurate and up-to-date information, the
              materials appearing on Walle Arena&apos;s website may include
              technical, typographical, or photographic errors. We do not warrant
              that any materials on the website are accurate, complete, or
              current.
            </p>
            <p className="mb-4">
              Walle Arena may make changes to the materials, information,
              tournament schedules, rules, or fees at any time without prior
              notice. However, we do not make any commitment to update materials
              or notify users of changes.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">12. Third-Party Links</h2>
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">12. Third-Party Links</h2>
            <p className="mb-4">
              Our website may contain links to third-party websites or services
              (such as Razorpay payment gateway, Cloudinary file storage) that
              are not owned or controlled by Walle Arena.
            </p>
            <p className="mb-4">
              Walle Arena has no control over and assumes no responsibility for
              the content, privacy policies, or practices of any third-party
              websites or services. We do not warrant the offerings of any of
              these entities/individuals or their websites.
            </p>
            <p className="mb-4">
              You acknowledge and agree that Walle Arena shall not be responsible
              or liable, directly or indirectly, for any damage or loss caused or
              alleged to be caused by or in connection with the use of any
              third-party content, goods, or services available through such
              websites.
            </p>
            <p className="mb-4">
              We strongly advise you to read the terms and conditions and privacy
              policies of any third-party websites or services that you visit.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">13. Termination</h2>
            <p className="mb-4">
              We reserve the right to terminate or suspend your account and access
              to the service immediately, without prior notice or liability, for
              any reason whatsoever, including but not limited to:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>Breach of these Terms of Service</li>
              <li>Providing false or misleading information</li>
              <li>Engaging in prohibited activities</li>
              <li>Violation of tournament rules or code of conduct</li>
              <li>Non-payment of fees</li>
              <li>At our sole discretion for any other reason</li>
            </ul>
            <p className="mb-4">
              Upon termination, your right to use the service will immediately
              cease. Sections of these Terms that by their nature should survive
              termination (including but not limited to disclaimer of warranties,
              limitation of liability, and governing law) shall survive
              termination.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">14. Indemnification</h2>
            <p className="mb-4">
              You agree to defend, indemnify, and hold harmless Walle Arena, its
              officers, directors, employees, agents, and third-party service
              providers from and against any claims, liabilities, damages,
              losses, costs, expenses, or fees (including reasonable
              attorneys&apos; fees) arising from:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>Your use or misuse of the service</li>
              <li>Your breach of these Terms of Service</li>
              <li>Your violation of any law or third-party rights</li>
              <li>Your content or information uploaded to the service</li>
              <li>Any fraudulent or illegal activities</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">15. Dispute Resolution and Governing Law</h2>
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">15. Dispute Resolution and Governing Law</h2>
            <p className="mb-4">
              These Terms of Service and any disputes arising out of or related
              to the use of this website or our services shall be governed by and
              construed in accordance with the laws of India, without regard to
              conflict of law principles.
            </p>
            <p className="mb-4">
              In the event of any dispute, claim, or controversy arising out of
              or relating to these Terms or the breach, termination, enforcement,
              interpretation, or validity thereof, the parties shall first
              attempt to resolve the dispute through good-faith negotiations.
            </p>
            <p className="mb-4">
              If the dispute cannot be resolved through negotiation within 30
              days, the dispute shall be subject to the exclusive jurisdiction of
              the courts located in [City, State], India.
            </p>
            <p className="mb-4">
              Nothing in this section shall prevent either party from seeking
              injunctive or other equitable relief from a court of competent
              jurisdiction to prevent actual or threatened infringement,
              misappropriation, or violation of intellectual property rights.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">16. Modifications to Terms</h2>
            <p className="mb-4">
              Walle Arena reserves the right to modify, update, or replace these
              Terms of Service at any time at our sole discretion. We will notify
              users of material changes by posting the updated Terms on our
              website and updating the &quot;Last updated&quot; date at the top
              of this page.
            </p>
            <p className="mb-4">
              Your continued use of the service after any changes to these Terms
              constitutes your acceptance of the new Terms. If you do not agree
              to the modified Terms, you must discontinue use of the service.
            </p>
            <p className="mb-4">
              It is your responsibility to review these Terms periodically for
              changes. We recommend checking this page each time you access the
              website.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">17. Severability</h2>
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">17. Severability</h2>
            <p className="mb-4">
              If any provision of these Terms is held to be invalid, illegal, or
              unenforceable by a court of competent jurisdiction, the remaining
              provisions shall continue in full force and effect. The invalid or
              unenforceable provision shall be replaced with a valid provision
              that most closely matches the intent of the original provision.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">18. Entire Agreement</h2>
            <p className="mb-4">
              These Terms of Service, together with our Privacy Policy, Refund
              and Return Policy, and Cancellation and Shipping Policy, constitute
              the entire agreement between you and Walle Arena regarding the use
              of our website and services, superseding any prior agreements
              between you and Walle Arena (including, but not limited to, any
              prior versions of the Terms of Service).
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">19. Waiver</h2>
            <p className="mb-4">
              The failure of Walle Arena to enforce any right or provision of
              these Terms shall not constitute a waiver of such right or
              provision. Any waiver of any provision of these Terms will be
              effective only if in writing and signed by Walle Arena.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">20. Contact Information</h2>
            <p className="mb-4">
              If you have any questions, concerns, or feedback about these Terms
              of Service, please contact us at:
            </p>
            <div className="bg-gray-100 p-4 rounded mb-4">
              <p>
                <strong>Walle Arena</strong>
              </p>
              <p className="mt-2">
                <strong>Registered Address:</strong>
                <br />
                304 Floor 3, 28 Devdarshan Enterprises
                <br />
                Agiary Lane, Zaveri Bazar, Kalbadevi
                <br />
                Mumbai, Maharashtra 400002, India
              </p>
              <p className="mt-2">
                <strong>Email:</strong> support@wallearena.com
              </p>
              <p>
                <strong>Customer Support Phone:</strong> +91 9833208066
              </p>
              <p>
                <strong>Website:</strong>{" "}
                <a
                  href="https://www.wallearena.com"
                  className="text-blue-600 hover:underline"
                >
                  www.wallearena.com
                </a>
              </p>
              <p className="mt-2 text-sm">
                Customer Support Hours: Monday to Friday, 10:00 AM - 6:00 PM IST
              </p>
            </div>
            <p className="mb-4">
              We aim to respond to all inquiries within 48 hours during business
              days.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">21. Acknowledgment</h2>
            <p className="mb-4">
              BY USING THIS WEBSITE AND OUR SERVICES, YOU ACKNOWLEDGE THAT YOU
              HAVE READ THESE TERMS OF SERVICE, UNDERSTAND THEM, AND AGREE TO BE
              BOUND BY THEM. IF YOU DO NOT AGREE TO THESE TERMS, YOU ARE NOT
              AUTHORIZED TO USE THIS WEBSITE OR OUR SERVICES.
            </p>
            <p>
              This document is published in accordance with the provisions of
              Rule 3(1) of the Information Technology (Intermediary Guidelines
              and Digital Media Ethics Code) Rules, 2021 that require publishing
              the rules and regulations, privacy policy, and terms of use for
              access or usage of the website.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
